# Generated by Django 4.2.5 on 2023-09-18 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('blood_group', models.CharField(choices=[('A+', 'A RhD Positive'), ('A-', 'A RhD Negative'), ('B+', 'B RhD Positive'), ('B-', 'B RhD Negative'), ('O+', 'O RhD Positive'), ('O-', 'O RhD Negative'), ('AB+', 'AB RhD Positive'), ('AB-', 'AB RhD Negative')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('date_of_birth', models.DateField(help_text='YYYY-MM-DD formate.')),
                ('max_age', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0, help_text='Height in Foot.Inch, For Example: 5.7')),
                ('weight', models.FloatField(default=0.0, help_text='Weight in kilograms')),
                ('bmi', models.FloatField(default=0.0)),
                ('is_ready_to_donate', models.BooleanField(default=False, help_text='Are you interested to donate blood?', verbose_name='is interested to donate blood')),
                ('next_donation_remaining_days', models.DateField(auto_now=True)),
                ('mobile_number', models.TextField(max_length=20, verbose_name='mobile number')),
                ('address', models.TextField(max_length=255, verbose_name='present address')),
                ('image', models.ImageField(upload_to='profile-pictures')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserBloodDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('donateDate', models.DateTimeField(auto_now_add=True)),
                ('bloodDoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donner', to=settings.AUTH_USER_MODEL)),
                ('bloodRecipients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Donation List',
                'verbose_name_plural': 'Blood Donation List',
            },
        ),
    ]
