# Generated by Django 4.2.5 on 2023-11-11 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblooddonate',
            old_name='bloodRecipients',
            new_name='blood_recipients',
        ),
        migrations.RenameField(
            model_name='userblooddonate',
            old_name='donateDate',
            new_name='donate_date',
        ),
        migrations.RemoveField(
            model_name='userblooddonate',
            name='bloodDoner',
        ),
        migrations.AddField(
            model_name='userblooddonate',
            name='blood_donner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='next_donation_remaining_days',
            field=models.DateField(auto_now_add=True),
        ),
    ]
