# Generated by Django 4.2.5 on 2023-11-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblooddonate',
            unique_together={('blood_recipients', 'blood_donner')},
        ),
    ]
