# Generated by Django 4.2.5 on 2023-11-25 16:31

from django.db import migrations, models
import users.utils.helper


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userblooddonate_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodneeded",
            name="description",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bloodneeded",
            name="coordinates",
            field=models.JSONField(
                blank=True, default=users.utils.helper.get_coordinates, null=True
            ),
        ),
    ]
