# Generated by Django 4.2.5 on 2023-11-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_bloodneeded_description_myuser_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodneeded",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userblooddonate",
            name="blood_recipients",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_blood_donate",
                to="users.bloodneeded",
            ),
        ),
    ]
