# Generated by Django 4.2.5 on 2023-11-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_bloodneeded_is_visible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevicetoken",
            name="device_token",
            field=models.CharField(max_length=255),
        ),
    ]
